### ISSUE TITLE
Homebridge crashing unexpectedly 

### ISSUE THREAD

**Issue by toellbe** [github9984/homebridge-xiaomi-purifier-3#1]
[Homebridge] TypeError: Cannot read property '0' of undefined
[Homebridge] at MiAirPurifier3.getLED (/home/hoobs/.hoobs/node_modules/homebridge-xiaomi-purifier-3/index.js:682:22)
[Homebridge] TypeError: Cannot read property '0' of undefined
[Homebridge] at MiAirPurifier3.getLED (/home/hoobs/.hoobs/node_modules/homebridge-xiaomi-purifier-3/index.js:682:22)
[Homebridge] [4/14/2020, 1:35:16 PM] undefined
[Homebridge] [4/14/2020, 1:35:16 PM] Got SIGTERM, shutting down service...

**Comment by github9984** [comment]
Do you have the global version or international version?
That error comes from when the code is getting the LED status. You can set the LED switch off in the config.json when setting up, but that means you'll lose that functionality to control in HomeKit.

**Comment by toellbe** [comment]
I use the global version bought in Europe. I will deactivate the switch and see if it helps.

Too bad - the switch was a nice feature.

**Comment by github9984** [comment]
i am also using global version. perhaps it's a different version to europe.

**Comment by toellbe** [comment]
And HomeBridge cashed if I slowly turn up the speed with my finger continuously pressed. Manual mode.

[Homebridge] Error: This callback function has already been called by someone else; it can only be called one time.
[Homebridge] at /home/hoobs/.hoobs/node_modules/@hoobs/hap/lib/util/once.js:12:13
[Homebridge] at /home/hoobs/.hoobs/node_modules/homebridge-xiaomi-purifier-3/index.js:496:6
[Homebridge] Error: This callback function has already been called by someone else; it can only be called one time.
[Homebridge] at /home/hoobs/.hoobs/node_modules/@hoobs/hap/lib/util/once.js:12:13
[Homebridge] at /home/hoobs/.hoobs/node_modules/homebridge-xiaomi-purifier-3/index.js:496:6

**Comment by github9984** [comment]
thanks for reporting that. I'll looking it when i get a chance.

**Comment by github9984** [comment]
update to the 1.5.2 version. bug regarding callback function has been fixed

**Comment by toellbe** [comment]
wow, Thanks. Works 👍
