### ISSUE TITLE
request: change main accessory or separate tiles

### ISSUE THREAD

**Issue by paqpaqpaq** [github9984/homebridge-xiaomi-purifier-3#11]
I found that this purifier is being shown as an air quality tile, with options underneath. This makes no sense to me.
Can this be made an air purifier instead, which can actually have a state? (on/off).
Or, alternatively, separate the tiles in order make them 2 accessories instead.

**Comment by adamrzanek** [comment]
Yes. I thinks it's strange

**Comment by paqpaqpaq** [comment]
#17
